# Generated by Django 5.2.13 on 2026-04-28 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name_ru', models.CharField(max_length=128)),
                ('name_ro', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'event_categories',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=512)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
            },
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_source_690504_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_categor_b43556_idx',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue_name',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_raw',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='event',
            name='last_scraped_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='raw_categories',
        ),
        migrations.RemoveField(
            model_name='event',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='event',
            name='source',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_links',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', through='api.EventCategory', to='api.category'),
        ),
        migrations.AddField(
            model_name='event',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.provider'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['provider', 'external_id'], name='events_provide_8ad30b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventcategory',
            unique_together={('event', 'category')},
        ),
    ]
